### PR TITLE
added maven archetype structure and gitignore

### PR DESCRIPTION
**Pull request by gkman**
@prathamMantri @dhirendracool1 @ProdigalTechnician 

Please look at these changes and make comments to them. 

Do not merge this

### CODE REVIEW

**Comment by ProdigalTechnician** [comment]
I'm looking at the changes and I really have nothing to add, but that's mostly because I'm not sure of the nature of a pull request as opposed to a branch. What exactly is being accomplished here?

**Comment by gkman** [comment]
So a Pull Request is a request from one developer to another/team to merge/join the code in their branch to the master/main branch. So you can go develop your code indepently of another and when you're done you put a PR up for people to comment on and make sure the code meets the requirements, usually decided by the team/a task for your job/the description of the PR. The requirements can be functionality/code style/code format/etc. 

So this PR is me saying here, I wrote a bunch of code for a maven project so that we can run and build our project based on the maven lifecycle and added codestyle/format plugins as well as build dependencies. Does this all look okay, is there anything people disagree with? 

This gives other developers in the team the opportunity/ability to comment on that before it is merged from the branch i personally was working on into the main branch where code should always work.

does that make sense?

**Comment by ProdigalTechnician** [comment]
Oh, you're asking if the code you posted is ok so you can push it to master; a final approval kind of thing. I completely misunderstood and didn't realize you were waiting for a response to move forward, and I would assume this goes for our teammates as well, though I can't speak for them. Yes, everything looks fine to me.

**Comment by gkman** [comment]
Yes that's exactly what I want. I want people's comments/approval/disapproval to merge or change the code. 

:+1: 

@ProdigalTechnician @prathamMantri @dhirendracool1 @singhridhima

**Comment by prathamMantri** [comment]
I haven't gone through code completely.
It looks good to me as well. If you are confident, then I don't have problem at all.

**Comment by gkman** [comment]
I'm going to merge this then. it can always be modified.

**Pull request merged**
